//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Ruinum.ECS/Core/Scripts/Input/UserInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInput"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""ed6ac180-f9bc-4fc6-929e-162955fb8ae2"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""5a6a1d68-0873-4811-a347-51c7cc292807"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""fbae91b0-0a73-47e1-b888-6606bbb8f023"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""43f94f69-87e6-4522-8031-ecf0c675f8e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""464a0bf6-c87b-481c-a6ac-85958149f2c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""638fe8f6-7dba-4d8e-8407-8f9ea776d1df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action0"",
                    ""type"": ""Button"",
                    ""id"": ""c245ae30-93a7-43b0-babe-3a46320d94ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action1"",
                    ""type"": ""Button"",
                    ""id"": ""bbd33646-a562-4de1-9012-5dd9ccd9e147"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button1"",
                    ""type"": ""Button"",
                    ""id"": ""2079ee22-abe4-4957-8afc-26d4b41e7052"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""fc452bc7-5229-4d1b-a4d9-e33e7c126392"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F1"",
                    ""type"": ""Button"",
                    ""id"": ""aaae860a-d72e-4d8e-a450-b56407ab4809"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F2"",
                    ""type"": ""Button"",
                    ""id"": ""72c8bc8e-c1b9-425b-bf4a-70cf0d003d6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""7b32c79d-fc59-49fe-bdd1-bea9223d20db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha1"",
                    ""type"": ""Button"",
                    ""id"": ""c762a2b6-bdd4-44c3-b1e8-6f05b6a77ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha2"",
                    ""type"": ""Button"",
                    ""id"": ""91d7fc6d-914b-4452-864a-fb199e584a0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha3"",
                    ""type"": ""Button"",
                    ""id"": ""3c73efd0-f9b8-44be-bb38-7d50bed4403f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdeb5d30-014f-4b63-91f6-41f34b328a59"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20cfceda-4e5a-4177-b8f7-f167558722ef"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ade0afe2-854e-44ef-9007-7130ceb16c5c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a167146-2dfc-4913-acc0-d30f5fb95b00"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6497fbaa-5f0c-410e-a2e9-0d60006b6b41"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""91ee5769-bdf8-40d0-bb61-46e7e41dbfd7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0883d50a-fda9-43b7-bb61-276b3ff5afdc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1c2199c8-7d70-48d0-9dac-259262181663"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""225a891d-5578-4fea-9164-4b2a3d950b60"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""152101cf-c530-461d-8458-4de85cdf2803"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a910f6ad-0079-4888-8deb-4c8505d5adbd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaae59b8-fd46-4294-a60d-73785db6317b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58240299-3881-4ccc-affa-cfca6a398c22"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7b1b26a-684f-4374-ab4c-f9830e9085d8"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58b07146-0cee-4874-8e7d-65d0782ec351"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dc29a8b-476c-48bd-9f37-069355cc7a2b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""599bb6f6-403e-4ab2-ac3f-fc47c6179f08"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd2e8f1d-dea0-4793-90f9-6e48a51ab5ed"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22c7c997-cc6b-4004-a335-08e8f618bc1b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GameSettings"",
            ""id"": ""64fd7605-6b94-4444-9ff2-1fca7c620957"",
            ""actions"": [
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""4cbd9acd-68df-4e8e-9d2c-77c3a3e0e3f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdb6dced-037a-4478-9c75-f36d7c08a744"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Look = m_Game.FindAction("Look", throwIfNotFound: true);
        m_Game_Move = m_Game.FindAction("Move", throwIfNotFound: true);
        m_Game_Jump = m_Game.FindAction("Jump", throwIfNotFound: true);
        m_Game_Esc = m_Game.FindAction("Esc", throwIfNotFound: true);
        m_Game_Interact = m_Game.FindAction("Interact", throwIfNotFound: true);
        m_Game_Action0 = m_Game.FindAction("Action0", throwIfNotFound: true);
        m_Game_Action1 = m_Game.FindAction("Action1", throwIfNotFound: true);
        m_Game_Button1 = m_Game.FindAction("Button1", throwIfNotFound: true);
        m_Game_Tab = m_Game.FindAction("Tab", throwIfNotFound: true);
        m_Game_F1 = m_Game.FindAction("F1", throwIfNotFound: true);
        m_Game_F2 = m_Game.FindAction("F2", throwIfNotFound: true);
        m_Game_Cancel = m_Game.FindAction("Cancel", throwIfNotFound: true);
        m_Game_Alpha1 = m_Game.FindAction("Alpha1", throwIfNotFound: true);
        m_Game_Alpha2 = m_Game.FindAction("Alpha2", throwIfNotFound: true);
        m_Game_Alpha3 = m_Game.FindAction("Alpha3", throwIfNotFound: true);
        // GameSettings
        m_GameSettings = asset.FindActionMap("GameSettings", throwIfNotFound: true);
        m_GameSettings_Esc = m_GameSettings.FindAction("Esc", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_Look;
    private readonly InputAction m_Game_Move;
    private readonly InputAction m_Game_Jump;
    private readonly InputAction m_Game_Esc;
    private readonly InputAction m_Game_Interact;
    private readonly InputAction m_Game_Action0;
    private readonly InputAction m_Game_Action1;
    private readonly InputAction m_Game_Button1;
    private readonly InputAction m_Game_Tab;
    private readonly InputAction m_Game_F1;
    private readonly InputAction m_Game_F2;
    private readonly InputAction m_Game_Cancel;
    private readonly InputAction m_Game_Alpha1;
    private readonly InputAction m_Game_Alpha2;
    private readonly InputAction m_Game_Alpha3;
    public struct GameActions
    {
        private @UserInput m_Wrapper;
        public GameActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Game_Look;
        public InputAction @Move => m_Wrapper.m_Game_Move;
        public InputAction @Jump => m_Wrapper.m_Game_Jump;
        public InputAction @Esc => m_Wrapper.m_Game_Esc;
        public InputAction @Interact => m_Wrapper.m_Game_Interact;
        public InputAction @Action0 => m_Wrapper.m_Game_Action0;
        public InputAction @Action1 => m_Wrapper.m_Game_Action1;
        public InputAction @Button1 => m_Wrapper.m_Game_Button1;
        public InputAction @Tab => m_Wrapper.m_Game_Tab;
        public InputAction @F1 => m_Wrapper.m_Game_F1;
        public InputAction @F2 => m_Wrapper.m_Game_F2;
        public InputAction @Cancel => m_Wrapper.m_Game_Cancel;
        public InputAction @Alpha1 => m_Wrapper.m_Game_Alpha1;
        public InputAction @Alpha2 => m_Wrapper.m_Game_Alpha2;
        public InputAction @Alpha3 => m_Wrapper.m_Game_Alpha3;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLook;
                @Move.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GameActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnJump;
                @Esc.started -= m_Wrapper.m_GameActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnEsc;
                @Interact.started -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Action0.started -= m_Wrapper.m_GameActionsCallbackInterface.OnAction0;
                @Action0.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnAction0;
                @Action0.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnAction0;
                @Action1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnAction1;
                @Action1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnAction1;
                @Action1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnAction1;
                @Button1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButton1;
                @Button1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButton1;
                @Button1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButton1;
                @Tab.started -= m_Wrapper.m_GameActionsCallbackInterface.OnTab;
                @Tab.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnTab;
                @Tab.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnTab;
                @F1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnF1;
                @F1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnF1;
                @F1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnF1;
                @F2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnF2;
                @F2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnF2;
                @F2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnF2;
                @Cancel.started -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnCancel;
                @Alpha1.started -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha1;
                @Alpha1.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha1;
                @Alpha1.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha1;
                @Alpha2.started -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha2;
                @Alpha2.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha2;
                @Alpha2.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha2;
                @Alpha3.started -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha3;
                @Alpha3.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha3;
                @Alpha3.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnAlpha3;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Action0.started += instance.OnAction0;
                @Action0.performed += instance.OnAction0;
                @Action0.canceled += instance.OnAction0;
                @Action1.started += instance.OnAction1;
                @Action1.performed += instance.OnAction1;
                @Action1.canceled += instance.OnAction1;
                @Button1.started += instance.OnButton1;
                @Button1.performed += instance.OnButton1;
                @Button1.canceled += instance.OnButton1;
                @Tab.started += instance.OnTab;
                @Tab.performed += instance.OnTab;
                @Tab.canceled += instance.OnTab;
                @F1.started += instance.OnF1;
                @F1.performed += instance.OnF1;
                @F1.canceled += instance.OnF1;
                @F2.started += instance.OnF2;
                @F2.performed += instance.OnF2;
                @F2.canceled += instance.OnF2;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Alpha1.started += instance.OnAlpha1;
                @Alpha1.performed += instance.OnAlpha1;
                @Alpha1.canceled += instance.OnAlpha1;
                @Alpha2.started += instance.OnAlpha2;
                @Alpha2.performed += instance.OnAlpha2;
                @Alpha2.canceled += instance.OnAlpha2;
                @Alpha3.started += instance.OnAlpha3;
                @Alpha3.performed += instance.OnAlpha3;
                @Alpha3.canceled += instance.OnAlpha3;
            }
        }
    }
    public GameActions @Game => new GameActions(this);

    // GameSettings
    private readonly InputActionMap m_GameSettings;
    private IGameSettingsActions m_GameSettingsActionsCallbackInterface;
    private readonly InputAction m_GameSettings_Esc;
    public struct GameSettingsActions
    {
        private @UserInput m_Wrapper;
        public GameSettingsActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Esc => m_Wrapper.m_GameSettings_Esc;
        public InputActionMap Get() { return m_Wrapper.m_GameSettings; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameSettingsActions set) { return set.Get(); }
        public void SetCallbacks(IGameSettingsActions instance)
        {
            if (m_Wrapper.m_GameSettingsActionsCallbackInterface != null)
            {
                @Esc.started -= m_Wrapper.m_GameSettingsActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_GameSettingsActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_GameSettingsActionsCallbackInterface.OnEsc;
            }
            m_Wrapper.m_GameSettingsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
            }
        }
    }
    public GameSettingsActions @GameSettings => new GameSettingsActions(this);
    public interface IGameActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAction0(InputAction.CallbackContext context);
        void OnAction1(InputAction.CallbackContext context);
        void OnButton1(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnF1(InputAction.CallbackContext context);
        void OnF2(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnAlpha1(InputAction.CallbackContext context);
        void OnAlpha2(InputAction.CallbackContext context);
        void OnAlpha3(InputAction.CallbackContext context);
    }
    public interface IGameSettingsActions
    {
        void OnEsc(InputAction.CallbackContext context);
    }
}
